### ISSUE TITLE
pollster not picking the region_name from ceilometer.conf

### ISSUE THREAD

**Issue by PrernaDembla** [SmartInfrastructures/ceilometer-fiware#3]
I am integrating ceilometer for noida region. We have  containerized openstack environment for each service.
For this, I have added [region] tag and region_name in [service_credentials] tag in ceilometer.conf in "ceilometer-central" container.  "ceilometer.conf" has been attached.

Pollster is not able to pick the region name from ceilometer.conf that is why it is picking the default endpoint at [0] index. 
http://git.openstack.org/cgit/openstack/keystoneauth/tree/keystoneauth1/access/service_catalog.py?h=stable/pike#n250
Line: 380
 if endpoint_data_list:
            return endpoint_data_list[0]

Output for "pollster_test_fiware_region":
Unable to establish connection to http://83.212.238.68:9696/v2.0/networks: HTTPConnectionPool(host='83.212.238.68', port=9696): Max retries exceeded with url: /v2.0/networks (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1128d30810>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Output for "pollster_test_fiware_host":
Unable to establish connection to http://fiware.infotec.net.mx:8774/v2/00000000000007442002913448960000/os-hosts: HTTPConnectionPool(host='fiware.infotec.net.mx', port=8774): Max retries exceeded with url: /v2/00000000000007442002913448960000/os-hosts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ae8e9a690>: Failed to establish a new connection: [Errno 110] Connection timed out',))

[ceilometer_conf.txt](https://github.com/SmartInfrastructures/ceilometer-fiware/files/2252940/ceilometer_conf.txt)

**Comment by acca** [comment]
Unfortunately the below solution proposed by Noida node cannot be applied since it implies to patch the Keystone internal component that is not part of the pollster.
I leave this information for a quick and dirty solution to anyone encountering same issue but the problem should be solved in the way the region is discovered by Ceilometer services and not in the pollster code.

Issue: Running pollster command pollster_test_fiware_region and pollster_test_fiware_region, gives connection time out. Reason being it was unable to pick region name from ceilometer conf file.

Solution: Add attached patch i.e. “adapter_patch” of adapter.py with given changes in “/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py” File in ceilometer-central

[adapter_patch.txt](https://github.com/SmartInfrastructures/ceilometer-fiware/files/2464751/adapter_patch.txt)
